# Generated by Django 4.2 on 2023-07-03 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('class_number', models.CharField(max_length=2)),
                ('lesson', models.CharField(max_length=2)),
                ('group', models.CharField(max_length=2)),
                ('semester', models.CharField(max_length=2)),
                ('faculty', models.CharField(max_length=2)),
                ('assistants', models.ManyToManyField(blank=True, related_name='assistant_sections', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='student_sections', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('class_number', 'lesson', 'group', 'semester', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='PendingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_eval', to='core.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_eval', to='core.section')),
            ],
            options={
                'unique_together': {('section', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=120, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evals', to='core.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('section', 'student', 'question')},
            },
        ),
    ]
