# Generated by Django 4.2 on 2023-04-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_roll_user_alter_user_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('class_number', models.CharField(max_length=2)),
                ('lesson', models.CharField(max_length=2)),
                ('group', models.CharField(max_length=2)),
                ('semester', models.CharField(max_length=2)),
                ('faculty', models.CharField(max_length=2)),
                ('assistants', models.ManyToManyField(related_name='assistant_sections', to='authentication.user')),
                ('students', models.ManyToManyField(related_name='student_sections', to='authentication.user')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='authentication.user')),
            ],
            options={
                'unique_together': {('class_number', 'lesson', 'group', 'semester', 'faculty')},
            },
        ),
    ]
