# Generated by Django 4.2 on 2023-05-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_answers_answer_rename_questions_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('section', 'student', 'question')},
        ),
    ]
