# Generated by Django 4.2 on 2023-05-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_answer_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingevaluation',
            unique_together={('section', 'question')},
        ),
    ]
