# Generated by Django 4.2 on 2023-05-26 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0009_alter_pendingevaluation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='assistant_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Roll',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
