# Generated by Django 4.2 on 2023-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_answer_student_alter_section_assistants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolestanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=9)),
                ('national_code', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
    ]
