# Generated by Django 4.2 on 2023-06-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_golestanuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golestanuser',
            old_name='national_code',
            new_name='national_id',
        ),
    ]
