# Generated by Django 4.2 on 2023-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_national_code_golestanuser_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golestanuser',
            name='national_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='golestanuser',
            name='student_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
