# Generated by Django 4.2 on 2023-07-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_golestanuser_national_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingevaluation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pendingevaluation',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pendingevaluation',
            name='section',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='section',
            name='assistants',
        ),
        migrations.RemoveField(
            model_name='section',
            name='students',
        ),
        migrations.RemoveField(
            model_name='section',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='PendingEvaluation',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
